<H1>Video 30 - MicroPython - Introduction to ulab</H1>

<H3>
Copyright (C) 2025 KW Services.</br>
Raspberry Pi Pico (RP2040)</br>
MicroPython v1.20.0-2504.g9fe842956 on 2025-04-04; Raspberry Pi Pico with RP2040</br>
MicroPython 1.24.1</br>
LVGL 9.3</br>
ulab 6.7.4</br>
MIT License</br>
ulab found at https://github.com/v923z/micropython-ulab as of 04 April 2025</br>
FP32</H3>

<H3>Connecting to Raspberry PI Pico</H3>

In [30]:
%disconnect

attempt to exit paste mode
[\r\x03\x02] b'\r\nMicroPython v1.20.0-2504.g9fe842956 on 2025-04-04; Raspberry Pi Pico with RP2040\r\nType "help()" for more information.\r\n>>> '
Closing serial Serial<id=0x20566a4dc00, open=True>(port='COM38', baudrate=115200, bytesize=8, parity='N', stopbits=1, timeout=0.5, xonxoff=False, rtscts=False, dsrdtr=False)


In [11]:
%serialconnect --port=COM38

Connecting to --port=COM38 --baud=115200 
Ready.


In [12]:
import ulab
print('You are running ulab version', ulab.__version__)
import sys
print("PyLang", sys.version_info, ";", sys.implementation)
import lvgl as lv
print("Running LVGL %d.%d" % (lv.version_major(), lv.version_minor() )  )

You are running ulab version 6.7.4-2D-c
PyLang (3, 4, 0) ; (name='micropython', version=(1, 24, 1, ''), _machine='Raspberry Pi Pico with RP2040', _mpy=4870)
Running LVGL 9.3


<H1>ulab import</H1>

In [13]:
from ulab import numpy as np

<H1>Numpy-like</H1)
<H2>The base class: ndarray</H2>

In [14]:
x1 = np.array([1,2,3])
print("x1 is:",x1)

num = []
for i in range(1,4):
    num.append(i)
x1 = np.array(num)
print("x1 is:",x1)

x1 is: array([1.0, 2.0, 3.0], dtype=float32)
x1 is: array([1.0, 2.0, 3.0], dtype=float32)


In [15]:
x2 = np.arange(0,10)
print(x2)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int16)


In [16]:
x3 = np.linspace(0, 10, num=5)
print(x3)

array([0.0, 2.5, 5.0, 7.5, 10.0], dtype=float32)


In [17]:
x4 = np.linspace(0, 10, num=100)
print(x4)

array([0.0, 0.1010101, 0.2020202, ..., 9.797992, 9.899002, 10.0], dtype=float32)


In [18]:
x5 = np.zeros(5)
print(x5)

array([0.0, 0.0, 0.0, 0.0, 0.0], dtype=float32)


In [19]:
x6 = np.ones(5)
print(x6)

array([1.0, 1.0, 1.0, 1.0, 1.0], dtype=float32)


In [20]:
x7 = np.ones(4)
print(x7)
x7.shape = (2,2)
print(x7)

array([1.0, 1.0, 1.0, 1.0], dtype=float32)
array([[1.0, 1.0],
       [1.0, 1.0]], dtype=float32)


In [21]:
x8 = np.array([[1,2],[3,4]])
print(x8)

array([[1.0, 2.0],
       [3.0, 4.0]], dtype=float32)


In [22]:
x9 = np.ones(3, dtype=np.uint8)
print(x9)
b = x9.tobytes()
print(b)

array([1, 1, 1], dtype=uint8)
bytearray(b'\x01\x01\x01')


<H1>Numpy-like Unary and Binary Operators</H1>

In [23]:
a = np.array([1,2,3])
b = np.array([4,5,6])
x10 = a+b
print(x10)

array([5.0, 7.0, 9.0], dtype=float32)


In [24]:
x10 = a*b
print(x10)

array([4.0, 10.0, 18.0], dtype=float32)


In [25]:
print("Length of x10:", len(x10) )

Length of x10: 3


<h1>Numpy Functions</h1>

In [26]:
temp = np.array([70,75,80])
xdate = np.array([1,3,6])
x11 = np.interp(4, xdate, temp)
print(x11)

array([76.66666], dtype=float32)


In [27]:
# prefers unix-formatted text file
x12 = np.loadtxt('Air.csv', max_rows=5, skiprows=0, delimiter=',' )
print(x12)
x12 = x12.flatten()
print(x12)
print("Length of numpy array x12:",len(x12))

array([[23.97, 27.42, 12.55, 22.63, 14.0, 26.43, 19.1, 17.28, 18.2, 22.07]], dtype=float32)
array([23.97, 27.42, 12.55, 22.63, 14.0, 26.43, 19.1, 17.28, 18.2, 22.07], dtype=float32)
Length of numpy array x12: 10


<h1>Scipy Functions</h1>

In [28]:
from ulab import scipy as spy

<h2>Perform Integration on</br>
$ f(x) = x^{2}$ + 2x + 1</h2>

In [29]:
f = lambda x: x**2 + 2*x + 1
result = spy.integrate.quad(f, 0, 5 )
print (f"result and tolerance = {result}")

result and tolerance = (71.66666, 9.305214e-05)
